#!/usr/bin/env python3
"""
Script to automatically update .vscode/c_cpp_properties.json with include paths
from compile_commands.json generated by CMake + Conan.

This ensures VS Code IntelliSense can find all dependencies including Conan packages.
"""

import json
import os
import re
import sys
from pathlib import Path
from typing import List, Set


def extract_include_paths_from_compile_commands(
    compile_commands_path: Path,
) -> Set[str]:
    """Extract all include paths from compile_commands.json"""
    include_paths = set()

    if not compile_commands_path.exists():
        print(f"Error: {compile_commands_path} not found")
        return include_paths

    with open(compile_commands_path, "r") as f:
        compile_commands = json.load(f)

    for entry in compile_commands:
        command = entry.get("command", "")

        # Extract -I and -isystem flags
        # Match patterns like: -I/path/to/include or -isystem /path/to/include
        include_patterns = [
            r"-I([^\s]+)",  # -I/path/to/include
            r"-isystem\s+([^\s]+)",  # -isystem /path/to/include
        ]

        for pattern in include_patterns:
            matches = re.findall(pattern, command)
            for match in matches:
                # Skip system SDK paths and other non-relevant paths
                if not any(
                    skip in match
                    for skip in ["/Applications/Xcode.app", "/usr/include"]
                ):
                    include_paths.add(match)

    return include_paths


def update_cpp_properties(workspace_root: Path, include_paths: Set[str]) -> None:
    """Update or create .vscode/c_cpp_properties.json with the extracted include paths"""

    vscode_dir = workspace_root / ".vscode"
    vscode_dir.mkdir(exist_ok=True)

    cpp_properties_path = vscode_dir / "c_cpp_properties.json"

    # Default configuration
    config = {
        "configurations": [
            {
                "name": "Mac",
                "includePath": [],
                "defines": [
                    "SPDLOG_COMPILED_LIB",
                    "SPDLOG_FMT_EXTERNAL",
                    "CARES_STATICLIB",
                ],
                "macFrameworkPath": [
                    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks"
                ],
                "compilerPath": "/usr/bin/clang++",
                "cStandard": "c17",
                "cppStandard": "c++17",
                "intelliSenseMode": "macos-clang-arm64",
                "compileCommands": "${workspaceFolder}/compile_commands.json",
            }
        ],
        "version": 4,
    }

    # Load existing configuration if it exists
    if cpp_properties_path.exists():
        try:
            with open(cpp_properties_path, "r") as f:
                existing_config = json.load(f)
                # Preserve existing settings but update include paths
                if (
                    "configurations" in existing_config
                    and existing_config["configurations"]
                ):
                    config["configurations"][0].update(
                        existing_config["configurations"][0]
                    )
        except json.JSONDecodeError:
            print(f"Warning: Invalid JSON in {cpp_properties_path}, creating new file")

    # Always ensure we have the workspace include paths
    base_include_paths = [
        "${workspaceFolder}/include",
        "${workspaceFolder}/build/generated",
    ]

    # Combine base paths with extracted paths
    all_include_paths = base_include_paths + sorted(list(include_paths))

    # Remove duplicates while preserving order
    seen = set()
    unique_include_paths = []
    for path in all_include_paths:
        if path not in seen:
            seen.add(path)
            unique_include_paths.append(path)

    config["configurations"][0]["includePath"] = unique_include_paths

    # Write the updated configuration
    with open(cpp_properties_path, "w") as f:
        json.dump(config, f, indent=4)

    print(f"Updated {cpp_properties_path}")
    print(f"Added {len(include_paths)} Conan include paths:")
    for path in sorted(include_paths):
        print(f"  {path}")


def main():
    """Main function"""
    # Get workspace root (script should be run from workspace root)
    workspace_root = Path.cwd()

    # Check if we're in the right directory
    if not (workspace_root / "CMakeLists.txt").exists():
        print(
            "Error: This script should be run from the workspace root (where CMakeLists.txt is located)"
        )
        sys.exit(1)

    compile_commands_path = workspace_root / "compile_commands.json"

    if not compile_commands_path.exists():
        print(
            "Error: compile_commands.json not found. Make sure you've built the project with CMake."
        )
        print("Run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON")
        sys.exit(1)

    # Extract include paths
    include_paths = extract_include_paths_from_compile_commands(compile_commands_path)

    if not include_paths:
        print("Warning: No include paths found in compile_commands.json")

    # Update c_cpp_properties.json
    update_cpp_properties(workspace_root, include_paths)

    print("\nDone! You should now:")
    print("1. Reload VS Code window (Cmd+Shift+P -> 'Developer: Reload Window')")
    print(
        "2. Or restart the C++ language server (Cmd+Shift+P -> 'C/C++: Reset IntelliSense Database')"
    )


if __name__ == "__main__":
    main()
